### ISSUE TITLE
open in wallet link not working as expected

### ISSUE THREAD

**Issue by cvarjao** [bcgov/BC-Wallet-Demo#63]
It seems like there is some code running on the client side waiting for the connection, however the browser no longer have focus, so it doesn't send the credential until switch back to browser

**Comment by wadeking98** [comment]
So the deeplink takes the user to the BCWallet app and puts the web browser in the background. The wallet starts it's side of the connection but the demo can't answer because the javascript can't run while the browser is in the background. I'll need to move the connection logic to the backend to fix this issue.

As a temporary work around while I fix this: once you click the deeplink and the connection starts, navigate back to the web browser for a moment, and then back to BCWallet and you should see a credential offer/proof request
